### ISSUE TITLE
Synchroniser les informations personnelles dans l'application et keycloak

### ISSUE THREAD

**Issue by bzg** [etalab/sill-web#3]
L'application ne connaît pas "Nom" et "Prénom" (ce qui n'est pas un souci pour l'instant) et Keycloak permet d'ajouter ces informations sans qu'elles soient stockées.  Le mieux est que Keycloak ne demande pas ces infos tant qu'on ne les utilise pas dans l'application.

Il faudrait que Keycloak demande l'affiliation pour pouvoir la mettre à jour.

**Comment by garronej** [comment]
NOTE for self:  

[This is the question and answer](https://stackoverflow.com/questions/62692620/how-to-update-custom-attribute-via-keycloak-rest-api)

Unfortunately we can't do it directly from the frontend because Keycloak's REST API require admin writes to perform this operation. Hence we need an API endpoint on our server and an extra configuration in onyxia-api: Keycloak admin barrer token.  

It can be worth it, beyond being able to edit `agencyName` to have a secure place where storing user informations.
